// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
import path from "path";

import dotenv from "dotenv";
dotenv.config({ path: path.join(__dirname, "../.env") });
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // using adapter method thats why off
    // url: env("DATABASE_URL"),
  },
});
